export enum AuthorityLevel {
  L1_DOGMATIC_TRUTH = 1,
  L2_SYSTEM_IMPACT = 2,
  L3_INCLUSION_STRATEGIC = 3,
  L4_SCIENTIFIC_VALIDATION = 4,
  L5_BINDING_JURISPRUDENCE = 5,
  L6_UNION_SENSORS = 6,
  L7_PRESS_SENSORS = 7,
}

export interface SourceFeed {
  level: AuthorityLevel;
  name: string;
  baseUrl: string;
  feedUrl?: string;
  pollingIntervalMs: number;
  selectorRules?: string[];
  isTriggerOnly: boolean;
  triggerTargetLevel?: AuthorityLevel;
}

export const SOURCE_MATRIX: SourceFeed[] = [
  {
    level: AuthorityLevel.L1_DOGMATIC_TRUTH,
    name: 'MIM - Ministero Istruzione e Merito',
    baseUrl: 'https://www.mim.gov.it',
    feedUrl: 'https://www.mim.gov.it/feed',
    pollingIntervalMs: 60_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L1_DOGMATIC_TRUTH,
    name: 'Gazzetta Ufficiale',
    baseUrl: 'https://www.gazzettaufficiale.it',
    feedUrl: 'https://www.gazzettaufficiale.it/feed',
    pollingIntervalMs: 120_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L1_DOGMATIC_TRUTH,
    name: 'Normattiva',
    baseUrl: 'https://www.normattiva.it',
    pollingIntervalMs: 300_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L1_DOGMATIC_TRUTH,
    name: 'INPS',
    baseUrl: 'https://www.inps.it',
    feedUrl: 'https://www.inps.it/feed',
    pollingIntervalMs: 120_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L1_DOGMATIC_TRUTH,
    name: 'ARAN',
    baseUrl: 'https://www.aranagenzia.it',
    pollingIntervalMs: 300_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L2_SYSTEM_IMPACT,
    name: 'INVALSI',
    baseUrl: 'https://www.invalsi.it',
    pollingIntervalMs: 300_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L2_SYSTEM_IMPACT,
    name: 'INDIRE',
    baseUrl: 'https://www.indire.it',
    pollingIntervalMs: 300_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L2_SYSTEM_IMPACT,
    name: 'Istituto Superiore di Sanità',
    baseUrl: 'https://www.iss.it',
    pollingIntervalMs: 300_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L2_SYSTEM_IMPACT,
    name: 'ISTAT',
    baseUrl: 'https://www.istat.it',
    pollingIntervalMs: 360_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L3_INCLUSION_STRATEGIC,
    name: 'Osservatorio Permanente Inclusione',
    baseUrl: 'https://www.osservatorioinclusione.it',
    pollingIntervalMs: 300_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L3_INCLUSION_STRATEGIC,
    name: 'Ministero per le Disabilità',
    baseUrl: 'https://www.disabilita.gov.it',
    pollingIntervalMs: 300_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L3_INCLUSION_STRATEGIC,
    name: 'OMS - Linee guida ICF',
    baseUrl: 'https://www.who.int',
    pollingIntervalMs: 600_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L4_SCIENTIFIC_VALIDATION,
    name: 'ERIC',
    baseUrl: 'https://eric.ed.gov',
    pollingIntervalMs: 600_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L4_SCIENTIFIC_VALIDATION,
    name: 'OECD Education',
    baseUrl: 'https://www.oecd.org/education',
    pollingIntervalMs: 600_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L4_SCIENTIFIC_VALIDATION,
    name: 'UNESCO Education',
    baseUrl: 'https://www.unesco.org/education',
    pollingIntervalMs: 600_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L4_SCIENTIFIC_VALIDATION,
    name: 'PubMed - Neuroscience/BES/DSA',
    baseUrl: 'https://pubmed.ncbi.nlm.nih.gov',
    pollingIntervalMs: 600_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L5_BINDING_JURISPRUDENCE,
    name: 'Giustizia Amministrativa',
    baseUrl: 'https://www.giustizia-amministrativa.it',
    pollingIntervalMs: 180_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L5_BINDING_JURISPRUDENCE,
    name: 'Corte Costituzionale',
    baseUrl: 'https://www.cortecostituzionale.it',
    pollingIntervalMs: 180_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L5_BINDING_JURISPRUDENCE,
    name: 'Corte di Cassazione',
    baseUrl: 'https://www.cortedicassazione.it',
    pollingIntervalMs: 180_000,
    isTriggerOnly: false,
  },
  {
    level: AuthorityLevel.L6_UNION_SENSORS,
    name: 'FLC CGIL',
    baseUrl: 'https://www.flcgil.it',
    feedUrl: 'https://www.flcgil.it/feed',
    pollingIntervalMs: 60_000,
    isTriggerOnly: true,
    triggerTargetLevel: AuthorityLevel.L1_DOGMATIC_TRUTH,
  },
  {
    level: AuthorityLevel.L6_UNION_SENSORS,
    name: 'CISL Scuola',
    baseUrl: 'https://www.cislscuola.it',
    feedUrl: 'https://www.cislscuola.it/feed',
    pollingIntervalMs: 60_000,
    isTriggerOnly: true,
    triggerTargetLevel: AuthorityLevel.L1_DOGMATIC_TRUTH,
  },
  {
    level: AuthorityLevel.L6_UNION_SENSORS,
    name: 'UIL Scuola',
    baseUrl: 'https://www.uilscuola.it',
    feedUrl: 'https://www.uilscuola.it/feed',
    pollingIntervalMs: 60_000,
    isTriggerOnly: true,
    triggerTargetLevel: AuthorityLevel.L1_DOGMATIC_TRUTH,
  },
  {
    level: AuthorityLevel.L6_UNION_SENSORS,
    name: 'SNALS Confsal',
    baseUrl: 'https://www.snals.it',
    pollingIntervalMs: 60_000,
    isTriggerOnly: true,
    triggerTargetLevel: AuthorityLevel.L1_DOGMATIC_TRUTH,
  },
  {
    level: AuthorityLevel.L6_UNION_SENSORS,
    name: 'ANIEF',
    baseUrl: 'https://www.anief.it',
    pollingIntervalMs: 60_000,
    isTriggerOnly: true,
    triggerTargetLevel: AuthorityLevel.L1_DOGMATIC_TRUTH,
  },
  {
    level: AuthorityLevel.L7_PRESS_SENSORS,
    name: 'Orizzonte Scuola',
    baseUrl: 'https://www.orizzontescuola.it',
    feedUrl: 'https://www.orizzontescuola.it/feed',
    pollingIntervalMs: 60_000,
    isTriggerOnly: true,
    triggerTargetLevel: AuthorityLevel.L1_DOGMATIC_TRUTH,
  },
  {
    level: AuthorityLevel.L7_PRESS_SENSORS,
    name: 'Tecnica della Scuola',
    baseUrl: 'https://www.tecnicadellascuola.it',
    feedUrl: 'https://www.tecnicadellascuola.it/feed',
    pollingIntervalMs: 60_000,
    isTriggerOnly: true,
    triggerTargetLevel: AuthorityLevel.L1_DOGMATIC_TRUTH,
  },
  {
    level: AuthorityLevel.L7_PRESS_SENSORS,
    name: 'Tuttoscuola',
    baseUrl: 'https://www.tuttoscuola.com',
    feedUrl: 'https://www.tuttoscuola.com/feed',
    pollingIntervalMs: 60_000,
    isTriggerOnly: true,
    triggerTargetLevel: AuthorityLevel.L1_DOGMATIC_TRUTH,
  },
];
